function createfigure(ymatrix1)
%CREATEFIGURE(ymatrix1)
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 11-Jul-2018 12:33:45

% Create figure
figure;

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create multiple lines using matrix input to bar
bar1 = bar(ymatrix1);
set(bar1(4),'DisplayName','00222 B2A');
set(bar1(3),'DisplayName','00222 A2B');
set(bar1(2),'DisplayName','00040 B2A');
set(bar1(1),'DisplayName','00040 A2B');

% Create ylabel
ylabel('Absolute Median');

% Create xlabel
xlabel('Coefficients');

% Create title
title('July 11 WGN 10 Mhz PA Comparison: 7th Order, 4 Taps');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XTick',[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17],...
    'XTickLabel',...
    {'','\beta_{1,1}','\beta_{1,2}','\beta_{1,3}','\beta_{1,4}','\beta_{3,1}','\beta_{3,2}','\beta_{3,3}','\beta_{3,4}','\beta_{5,1}','\beta_{5,2}','\beta_{5,3}','\beta_{5,4}','\beta_{7,1}','\beta_{7,2}','\beta_{7,3}','\beta_{7,4}',''});
% Create legend
legend(axes1,'show');

